name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # 【新增】让云端全自动为你生成 Android 底层打包目录，你本地完全不用管！
      - name: Generate Native Code (Prebuild)
        run: npx expo prebuild --clean --no-install

      # 自动增加版本号脚本
      - name: Bump Version
        run: npm version patch --no-git-tag-version

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}